# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Dominus Veritas
paginate:       5
baseurl:        ""
url:            "https://ldemattos.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Leonardo M. N. de Mattos 
  url:          https://ldemattos.github.io
  email:        leonardo@mattos.eng.br

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
